create extension if not exists pgcrypto;
create table if not exists public.exercises (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, muscle_group text not null, load_type text not null, notes text not null default '', created_at timestamptz not null default now());
create table if not exists public.routines (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, muscle_group text not null, created_at timestamptz not null default now());
create table if not exists public.routine_exercises (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, routine_id uuid not null references public.routines(id) on delete cascade, exercise_id uuid not null references public.exercises(id) on delete cascade, order_index int not null default 0, default_weight numeric not null default 0, default_band_name text not null default '');
create table if not exists public.workouts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, date timestamptz not null default now(), title text not null, notes text not null default '', is_completed boolean not null default false);
create table if not exists public.workout_exercises (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_id uuid not null references public.workouts(id) on delete cascade, name text not null, muscle_group text not null, load_type text not null, order_index int not null default 0, note text not null default '');
create table if not exists public.workout_sets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_exercise_id uuid not null references public.workout_exercises(id) on delete cascade, order_index int not null default 0, repetitions int not null default 10, weight numeric not null default 0, band_name text not null default '', is_completed boolean not null default false);
create table if not exists public.body_measurements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, date date not null default current_date, waist numeric not null default 0, chest numeric not null default 0, relaxed_arm numeric not null default 0, flexed_arm numeric not null default 0, thigh numeric not null default 0, hips numeric not null default 0, notes text not null default '');

alter table public.exercises enable row level security; alter table public.routines enable row level security; alter table public.routine_exercises enable row level security; alter table public.workouts enable row level security; alter table public.workout_exercises enable row level security; alter table public.workout_sets enable row level security; alter table public.body_measurements enable row level security;
do $$ declare t text; begin foreach t in array array['exercises','routines','routine_exercises','workouts','workout_exercises','workout_sets','body_measurements'] loop execute format('drop policy if exists owner_all on public.%I',t); execute format('create policy owner_all on public.%I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)',t); end loop; end $$;

create or replace function public.seed_forgefit_for_user() returns void language plpgsql security invoker as $$
declare u uuid:=auth.uid(); chest_id uuid:=gen_random_uuid(); back_id uuid:=gen_random_uuid(); legs_id uuid:=gen_random_uuid(); e uuid; begin
 if u is null or exists(select 1 from public.exercises where user_id=u) then return; end if;
 insert into public.routines(id,user_id,name,muscle_group) values(chest_id,u,'Pecho','Pecho'),(back_id,u,'Espalda','Espalda'),(legs_id,u,'Pierna','Pierna');
 insert into public.exercises(user_id,name,muscle_group,load_type) values
 (u,'Press libre','Pecho','Barra · peso total'),(u,'Press inclinado con mancuernas','Pecho','Mancuernas · cada una'),(u,'Poleas de pecho','Pecho','Máquina/polea · peso seleccionado'),(u,'Tríceps con barra','Tríceps','Máquina/polea · peso seleccionado'),(u,'Jalón al pecho','Espalda','Máquina/polea · peso seleccionado'),(u,'Dominada asistida','Espalda','Dominada asistida · tipo de goma'),(u,'Pullover','Espalda','Máquina/polea · peso seleccionado'),(u,'Sentadilla','Pierna','Barra · peso total'),(u,'Zancada','Pierna','Mancuernas · cada una'),(u,'Glúteo','Glúteo','Máquina/polea · peso seleccionado'),(u,'Sentadilla Smith','Pierna','Barra · peso total');
 insert into public.routine_exercises(user_id,routine_id,exercise_id,order_index,default_weight,default_band_name)
 select u, case when name in ('Press libre','Press inclinado con mancuernas','Poleas de pecho','Tríceps con barra') then chest_id when name in ('Jalón al pecho','Dominada asistida','Pullover') then back_id else legs_id end,id,
 case name when 'Press libre' then 0 when 'Press inclinado con mancuernas' then 1 when 'Poleas de pecho' then 2 when 'Tríceps con barra' then 3 when 'Jalón al pecho' then 0 when 'Dominada asistida' then 1 when 'Pullover' then 2 when 'Sentadilla' then 0 when 'Zancada' then 1 when 'Glúteo' then 2 else 3 end,
 case name when 'Press libre' then 5 when 'Press inclinado con mancuernas' then 5 when 'Tríceps con barra' then 10 when 'Jalón al pecho' then 40 when 'Pullover' then 20 when 'Sentadilla' then 5 when 'Zancada' then 2.5 when 'Glúteo' then 10 else 0 end,
 case when name='Dominada asistida' then 'Dos gomas' else '' end from public.exercises where user_id=u;
end $$;
grant execute on function public.seed_forgefit_for_user() to authenticated;
